[package]
name = "noir_note"
version = "0.1.0"
description = "Minimal desktop workspace for notes and documents"
authors = ["Aleksandr Minkin"]
edition = "2021"
license = "MIT"
repository = "https://github.com/minkinad/noir-note"

[lib]
name = "noir_note_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.2.0", features = [] }

[dependencies]
chrono = { version = "0.4.42", features = ["serde"] }
rusqlite = { version = "0.40.2", features = ["bundled"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
tauri = { version = "2.9.1", features = [] }
tauri-plugin-window-state = "2.4.0"
thiserror = "2.0.17"

[profile.release]
lto = true
codegen-units = 1
strip = true
panic = "abort"
